name: Tests

on:
  push:
    branches: [main, dev, "release/*"]
  pull_request:
    branches: [main, dev, "release/*"]

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: cimg/node:22.13

    steps:
      - uses: actions/checkout@v4

      - name: Versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Tests (Vitest)
        run: npm run test
